//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Adapters.ControllerAdapters.Services.Game
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameDTO", Namespace="http://schemas.datacontract.org/2004/07/Hangman.Services.Models.DTO")]
    public partial class GameDTO : object
    {
        
        private string ChallengerEmailField;
        
        private string ChallengerNameField;
        
        private System.DateTime CreationDateField;
        
        private string CreatorEmailField;
        
        private string CreatorNameField;
        
        private string GameCodeField;
        
        private string LanguageField;
        
        private string StatusField;
        
        private string WordENField;
        
        private string WordESField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChallengerEmail
        {
            get
            {
                return this.ChallengerEmailField;
            }
            set
            {
                this.ChallengerEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChallengerName
        {
            get
            {
                return this.ChallengerNameField;
            }
            set
            {
                this.ChallengerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorEmail
        {
            get
            {
                return this.CreatorEmailField;
            }
            set
            {
                this.CreatorEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorName
        {
            get
            {
                return this.CreatorNameField;
            }
            set
            {
                this.CreatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameCode
        {
            get
            {
                return this.GameCodeField;
            }
            set
            {
                this.GameCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WordEN
        {
            get
            {
                return this.WordENField;
            }
            set
            {
                this.WordENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WordES
        {
            get
            {
                return this.WordESField;
            }
            set
            {
                this.WordESField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hangman.Adapters.ControllerAdapters.Services.Game.IGameServices")]
    public interface IGameServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/CreateGame", ReplyAction="http://tempuri.org/IGameServices/CreateGameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> CreateGameAsync(Hangman.Adapters.ControllerAdapters.Services.Game.GameDTO newGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetCategoriesList", ReplyAction="http://tempuri.org/IGameServices/GetCategoriesListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetCategoriesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetWordsList", ReplyAction="http://tempuri.org/IGameServices/GetWordsListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetWordsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/SetChallenger", ReplyAction="http://tempuri.org/IGameServices/SetChallengerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> SetChallengerAsync(string gameCode, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/SetGameStatus", ReplyAction="http://tempuri.org/IGameServices/SetGameStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> SetGameStatusAsync(string gameCode, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetWaitingGames", ReplyAction="http://tempuri.org/IGameServices/GetWaitingGamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetWaitingGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetPlayerType", ReplyAction="http://tempuri.org/IGameServices/GetPlayerTypeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetPlayerTypeAsync(string email, string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetLanguagesList", ReplyAction="http://tempuri.org/IGameServices/GetLanguagesListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetLanguagesListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IGameServicesChannel : Hangman.Adapters.ControllerAdapters.Services.Game.IGameServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class GameServicesClient : System.ServiceModel.ClientBase<Hangman.Adapters.ControllerAdapters.Services.Game.IGameServices>, Hangman.Adapters.ControllerAdapters.Services.Game.IGameServices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GameServicesClient() : 
                base(GameServicesClient.GetDefaultBinding(), GameServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGameServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(GameServicesClient.GetBindingForEndpoint(endpointConfiguration), GameServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GameServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GameServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> CreateGameAsync(Hangman.Adapters.ControllerAdapters.Services.Game.GameDTO newGame)
        {
            return base.Channel.CreateGameAsync(newGame);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetCategoriesListAsync()
        {
            return base.Channel.GetCategoriesListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetWordsListAsync()
        {
            return base.Channel.GetWordsListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> SetChallengerAsync(string gameCode, string email)
        {
            return base.Channel.SetChallengerAsync(gameCode, email);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> SetGameStatusAsync(string gameCode, string status)
        {
            return base.Channel.SetGameStatusAsync(gameCode, status);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetWaitingGamesAsync()
        {
            return base.Channel.GetWaitingGamesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetPlayerTypeAsync(string email, string gameCode)
        {
            return base.Channel.GetPlayerTypeAsync(email, gameCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetLanguagesListAsync()
        {
            return base.Channel.GetLanguagesListAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGameServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGameServices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51239/Communications/GameServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GameServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGameServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GameServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGameServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGameServices,
        }
    }
}
