<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\Nunito\Nunito-Italic-VariableFont_wght.ttf" />
    <None Remove="Resources\Fonts\Nunito\Nunito-VariableFont_wght.ttf" />
    <None Remove="Resources\Images\Ahorcado.png" />
    <None Remove="Resources\Images\calendar_icon.png" />
    <None Remove="Resources\Images\closed_door.png" />
    <None Remove="Resources\Images\Head.png" />
    <None Remove="Resources\Images\LeftArm.png" />
    <None Remove="Resources\Images\LeftLeg.png" />
    <None Remove="Resources\Images\open_door.png" />
    <None Remove="Resources\Images\Pole.png" />
    <None Remove="Resources\Images\profile_icon.png" />
    <None Remove="Resources\Images\RightArm.png" />
    <None Remove="Resources\Images\RightLeg.png" />
    <None Remove="Resources\Images\Torso.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hangman.Adapters\Hangman.Adapters.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Nunito\Nunito-Italic-VariableFont_wght.ttf" />
    <Resource Include="Resources\Fonts\Nunito\Nunito-VariableFont_wght.ttf" />
    <Resource Include="Resources\Images\Ahorcado.png" />
    <Resource Include="Resources\Images\calendar_icon.png" />
    <Resource Include="Resources\Images\closed_door.png" />
    <Resource Include="Resources\Images\Head.png" />
    <Resource Include="Resources\Images\LeftArm.png" />
    <Resource Include="Resources\Images\LeftLeg.png" />
    <Resource Include="Resources\Images\open_door.png" />
    <Resource Include="Resources\Images\Pole.png" />
    <Resource Include="Resources\Images\profile_icon.png" />
    <Resource Include="Resources\Images\RightArm.png" />
    <Resource Include="Resources\Images\RightLeg.png" />
    <Resource Include="Resources\Images\Torso.png" />
  </ItemGroup>

</Project>
