<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\Nunito\Nunito-Italic-VariableFont_wght.ttf" />
    <None Remove="Resources\Fonts\Nunito\Nunito-VariableFont_wght.ttf" />
    <None Remove="Resources\Images\Pole.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Nunito\Nunito-Italic-VariableFont_wght.ttf" />
    <Resource Include="Resources\Fonts\Nunito\Nunito-VariableFont_wght.ttf" />
    <Resource Include="Resources\Images\Pole.png" />
  </ItemGroup>

</Project>
