//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Adapters.ControllerAdapters.Services.Player
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Hangman.Services.Models.DTO")]
    public partial class PlayerDTO : object
    {
        
        private System.DateTime BirthDateField;
        
        private string EmailField;
        
        private string FirstLastNameField;
        
        private string NameField;
        
        private string PasswordField;
        
        private string SecondLastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLastName
        {
            get
            {
                return this.FirstLastNameField;
            }
            set
            {
                this.FirstLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName
        {
            get
            {
                return this.SecondLastNameField;
            }
            set
            {
                this.SecondLastNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hangman.Adapters.ControllerAdapters.Services.Player.IPlayerServices")]
    public interface IPlayerServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/LogIn", ReplyAction="http://tempuri.org/IPlayerServices/LogInResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> LogInAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/SignUp", ReplyAction="http://tempuri.org/IPlayerServices/SignUpResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> SignUpAsync(Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/UpdateProfile", ReplyAction="http://tempuri.org/IPlayerServices/UpdateProfileResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> UpdateProfileAsync(Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/GetPlayedGames", ReplyAction="http://tempuri.org/IPlayerServices/GetPlayedGamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetPlayedGamesAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IPlayerServicesChannel : Hangman.Adapters.ControllerAdapters.Services.Player.IPlayerServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class PlayerServicesClient : System.ServiceModel.ClientBase<Hangman.Adapters.ControllerAdapters.Services.Player.IPlayerServices>, Hangman.Adapters.ControllerAdapters.Services.Player.IPlayerServices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PlayerServicesClient() : 
                base(PlayerServicesClient.GetDefaultBinding(), PlayerServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPlayerServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayerServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(PlayerServicesClient.GetBindingForEndpoint(endpointConfiguration), PlayerServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayerServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PlayerServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayerServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PlayerServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> LogInAsync(string email, string pass)
        {
            return base.Channel.LogInAsync(email, pass);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> SignUpAsync(Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO player)
        {
            return base.Channel.SignUpAsync(player);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> UpdateProfileAsync(Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO player)
        {
            return base.Channel.UpdateProfileAsync(player);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetPlayedGamesAsync(string email)
        {
            return base.Channel.GetPlayedGamesAsync(email);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPlayerServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPlayerServices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51239/Communications/PlayerServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PlayerServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPlayerServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PlayerServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPlayerServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPlayerServices,
        }
    }
}
