//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Adapters.ControllerAdapters.Services.Player
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Hangman.Services.Models.DTO")]
    public partial class PlayerDTO : object
    {
        
        private System.DateTime BirthDateField;
        
        private string EmailField;
        
        private string FirstLastNameField;
        
        private string NameField;
        
        private string PasswordField;
        
        private int ResponseCodeField;
        
        private string SecondLastNameField;
        
        private string TelephoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLastName
        {
            get
            {
                return this.FirstLastNameField;
            }
            set
            {
                this.FirstLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName
        {
            get
            {
                return this.SecondLastNameField;
            }
            set
            {
                this.SecondLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone
        {
            get
            {
                return this.TelephoneField;
            }
            set
            {
                this.TelephoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameDTO", Namespace="http://schemas.datacontract.org/2004/07/Hangman.Services.Models.DTO")]
    public partial class GameDTO : object
    {
        
        private string ChallengerEmailField;
        
        private string ChallengerNameField;
        
        private System.DateTime CreationDateField;
        
        private string CreatorEmailField;
        
        private string CreatorNameField;
        
        private string GameCodeField;
        
        private string LanguageField;
        
        private int ResponseCodeField;
        
        private string StatusEnField;
        
        private string StatusEsField;
        
        private int WaitingTimeField;
        
        private string WordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChallengerEmail
        {
            get
            {
                return this.ChallengerEmailField;
            }
            set
            {
                this.ChallengerEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChallengerName
        {
            get
            {
                return this.ChallengerNameField;
            }
            set
            {
                this.ChallengerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorEmail
        {
            get
            {
                return this.CreatorEmailField;
            }
            set
            {
                this.CreatorEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorName
        {
            get
            {
                return this.CreatorNameField;
            }
            set
            {
                this.CreatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameCode
        {
            get
            {
                return this.GameCodeField;
            }
            set
            {
                this.GameCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusEn
        {
            get
            {
                return this.StatusEnField;
            }
            set
            {
                this.StatusEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusEs
        {
            get
            {
                return this.StatusEsField;
            }
            set
            {
                this.StatusEsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WaitingTime
        {
            get
            {
                return this.WaitingTimeField;
            }
            set
            {
                this.WaitingTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Word
        {
            get
            {
                return this.WordField;
            }
            set
            {
                this.WordField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hangman.Adapters.ControllerAdapters.Services.Player.IPlayerServices")]
    public interface IPlayerServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/LogIn", ReplyAction="http://tempuri.org/IPlayerServices/LogInResponse")]
        System.Threading.Tasks.Task<Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO> LogInAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/SignUp", ReplyAction="http://tempuri.org/IPlayerServices/SignUpResponse")]
        System.Threading.Tasks.Task<Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO> SignUpAsync(Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/UpdateProfile", ReplyAction="http://tempuri.org/IPlayerServices/UpdateProfileResponse")]
        System.Threading.Tasks.Task<Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO> UpdateProfileAsync(Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/GetPlayedGames", ReplyAction="http://tempuri.org/IPlayerServices/GetPlayedGamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Hangman.Adapters.ControllerAdapters.Services.Player.GameDTO>> GetPlayedGamesAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IPlayerServicesChannel : Hangman.Adapters.ControllerAdapters.Services.Player.IPlayerServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class PlayerServicesClient : System.ServiceModel.ClientBase<Hangman.Adapters.ControllerAdapters.Services.Player.IPlayerServices>, Hangman.Adapters.ControllerAdapters.Services.Player.IPlayerServices
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PlayerServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(PlayerServicesClient.GetBindingForEndpoint(endpointConfiguration), PlayerServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayerServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PlayerServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayerServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PlayerServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO> LogInAsync(string email, string pass)
        {
            return base.Channel.LogInAsync(email, pass);
        }
        
        public System.Threading.Tasks.Task<Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO> SignUpAsync(Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO player)
        {
            return base.Channel.SignUpAsync(player);
        }
        
        public System.Threading.Tasks.Task<Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO> UpdateProfileAsync(Hangman.Adapters.ControllerAdapters.Services.Player.PlayerDTO player)
        {
            return base.Channel.UpdateProfileAsync(player);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Hangman.Adapters.ControllerAdapters.Services.Player.GameDTO>> GetPlayedGamesAsync(string email)
        {
            return base.Channel.GetPlayedGamesAsync(email);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPlayerServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IPlayerServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPlayerServices))
            {
                return new System.ServiceModel.EndpointAddress("http://hangmanservices.azurewebsites.net/Communications/PlayerServices.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IPlayerServices))
            {
                return new System.ServiceModel.EndpointAddress("https://hangmanservices.azurewebsites.net/Communications/PlayerServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPlayerServices,
            
            BasicHttpsBinding_IPlayerServices,
        }
    }
}
